[build]
  # Directory to deploy
  publish = "dist"
  
  # Command to build the project
  command = "npm run build"

# Specify the Node.js version (optional, but recommended)
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8.19.4"

# Settings for Netlify Dev (optional)
[dev]
  # Point to the Vite dev server
  framework = "vite"
  targetPort = 3000
  port = 8888

# Redirect all routes to the index.html (for single-page apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
